### ISSUE TITLE
Error in DISK_PATTERN regex

### ISSUE THREAD

**Issue by philboltt** [sqlboy/fileseq#1]
The on-disk regex pattern fails for the following case:

``` python
>>> import fileseq, re
>>> pattern = re.compile(fileseq.all._ON_DISK_PATTERN)
>>> pattern.match('foo.r1.bar/fbx').groups()
(None, 'foo.r', '1', '.bar/fbx')
````

This causes errant values to be introduced in the findSequencesOnDisk() method, ultimately resulting in a parsing exception.

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fileseq/all.py", line 357, in findSequencesOnDisk
    result.append(FileSequence(seq))
  File "fileseq/all.py", line 167, in __init__
    self.__frameSet = FrameSet(m.group(3))
  File "fileseq/all.py", line 79, in __init__
    raise ParseException("Failed to parse frame range: %s on part '%s'" % (frange, part))
fileseq.all.ParseException: Failed to parse frame range: x on part 'x'
```

**Comment by justinfx** [comment]
I've just tested this case against HEAD and it seems to be resolved with the massive number of changes that have taken place to the regular expressions and parsing logic:

```python
>>> pattern.match('foo.r1.bar/fbx').groups()
('foo.r1.bar/', 'fbx', None, None)
```

This looks to be the expected results, since it was able to parse a dirname, basename, and then no frame range or extension.  I will close this issue, but we can reopen if you find there are still edge cases.
