### ISSUE TITLE
Add is_consecutive() to FrameSet class

### ISSUE THREAD

**Issue by Narann** [sqlboy/fileseq#51]
Hi everyone!

We try to find a way to know if there are "holes" inside a given `FrameSet`.

The only way we have right now is to unroll the whole `FrameSet` and compare it to another `FrameSet` generated with `start()` and `end()`:

```python
>>> import fileseq
>>> fs = fileseq.FrameSet("410-470x30")
>>> set(list(fs)) == set(list(fileseq.FrameSet("{}-{}".format(fs.start(), fs.end()))
False  # there is holes between start and end!
```

Maybe `is_truncated()` is not the good name but you get the idea, what do you think about adding such method?

Regards,

Dorian

**Comment by justinfx** [comment]
Truncated may not be the right term here, because there are three different cases for the range, and while "truncated" implies a problem, some cases are actually expected.

# Consecutive: "1-10"
# Contiguous stepping: "1-10x2"
# Non-contiguous stepping: "1-4x2,6-10x3"

People usually expect contiguous stepping in a normal workflow when they run shots on 10s or whatever. So calling it truncated implies an error. At least that's how I interpret it. Maybe you are looking for find out if it's non-consecutive? Or if it's contiguous vs Non-contiguous stepping?

That aside, there is a much cheaper way to check what you wanted without having to construct a new fully filled range.

```
len(fs) == abs(fs.end()-fs.start()+1)
```

That would compare the actual number of frames to the sequential range and tell you if it has any stepping.

**Comment by Narann** [comment]
Thanks for the smaller snippet.

About the term and from what you wrote, maybe `is_consecutive` is the right term (actually my colleague also use this term).
```python
>>> import fileseq
>>> fileseq.FrameSet("410-470x30").is_consecutive
False
>>> fileseq.FrameSet("410-470").is_consecutive
True
```
IMHO, it make the code easier to understand:
```python
>>> import fileseq
>>> fs = fileseq.FrameSet("410-470x30")
>>> fs.is_consecutive
```
Looks easier to read than:
```python
len(fs) == abs(fs.end()-fs.start())+1
```
You're the boss, do what you want, I was just surprised nobody bump with such request before. :)

Keep the good work!

**Comment by justinfx** [comment]
If it's convenient, I can add it. Maybe needing to know if a sequence is
consecutive is specific to certain workflows and people either haven't
needed it or have done the check I listed.

**Comment by Narann** [comment]
No hurry, we can wait to see if other peoples ask for this.

**Comment by justinfx** [comment]
Let me know if #52 works for you
